name: get_system_info_rest
label: Get PAN-OS System Information

description: |
  This skillet demonstrates a simple REST api call to a PAN-OS NGFW to gather it's system information

type: rest

extends:

labels:
  collection: Silliker

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: ip_address
  - name: api_key
    description: API Key
    default: abc123
    type_hint: text
  - name: TARGET_USERNAME
    description: API User
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: API Password
    default: admin
    type_hint: password

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    # this should output capturing which will set a variable called 'api_key' in the workflow, which can be referenced
    # in a skillet called after this one, any variable with a name called api_key will be prepopulated with the
    # value that is captured from the output of this xml api command
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key
  - name: system_info
    path: https://{{ TARGET_IP }}/api/?type=op&cmd=<show><system><info></info></system></show>&key={{ api_key }}
    output_type: xml
    outputs:
      - name: hostname
        capture_pattern: result/system/hostname
      - name: uptime
        capture_pattern: result/system/uptime
      - name: sw_version
        capture_pattern: result/system/sw-version

