# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: authPolicy
# label used for menu selection
label: auth policy
description: Create an authentication policy

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - identityCollection

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: tag_name
    description: Tag Name
    default: yourTag
    type_hint: text
  - name: tag_description
    description: Tag Description
    default: tag_description
    type_hint: text
  - name: tag_color
    description: Tag Colors
    default: choices
    type_hint: dropdown
    dd_list:
      - key: Red
        value: color1
      - key: Blue
        value: color3
      - key: Green
        value: color22
  - name: edl_name
    description: EDL Name
    default: yourEdlName
    type_hint: text
  - name: edl_description
    description: Description
    default: description
    type_hint: text
  - name: edl_url
    description: EDL URL
    default: http://your.host.name/edl.txt
    type_hint: text
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
  - name: edl
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/external-list
    file: edl.xml
  - name: security_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
    file: security_rules.xml

# ---------------------------------------------------------------------
# end of snippets section

